/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wepet.wepet2.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.IntegerWrapper;
import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.wepet.wepet2.service.Wepet2QueryExecutorService;
import com.wepet.wepet2.models.query.*;

@RestController(value = "Wepet2.QueryExecutionController")
@RequestMapping("/wepet2/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private Wepet2QueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @DeleteMapping(value = "/queries/deleteAnimalById")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "delete an animal")
    public IntegerWrapper executeDeleteAnimalById(@RequestParam(value = "id") String id, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: deleteAnimalById");
        Integer _result = queryService.executeDeleteAnimalById(id);
        LOGGER.debug("got the result for named query: deleteAnimalById, result:{}", _result);
        return new IntegerWrapper(_result);
    }

    @GetMapping(value = "/queries/getAnimalById")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Get an animal by id")
    public Page<GetAnimalByIdResponse> executeGetAnimalById(@RequestParam(value = "id") String id, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: getAnimalById");
        Page<GetAnimalByIdResponse> _result = queryService.executeGetAnimalById(id, pageable);
        LOGGER.debug("got the result for named query: getAnimalById, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file url for query getAnimalById")
    @PostMapping(value = "/queries/getAnimalById/export")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGetAnimalById(@RequestParam(value = "id") String id, @RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: getAnimalById");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "getAnimalById";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportGetAnimalById(id,  exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

    @DeleteMapping(value = "/queries/deleteOrgFromLogin")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "used to delete the organization from login table")
    public IntegerWrapper executeDeleteOrgFromLogin(@RequestParam(value = "email") String email, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: deleteOrgFromLogin");
        Integer _result = queryService.executeDeleteOrgFromLogin(email);
        LOGGER.debug("got the result for named query: deleteOrgFromLogin, result:{}", _result);
        return new IntegerWrapper(_result);
    }

}