/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wepet.wepet2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.wepet.wepet2.models.query.*;

public interface Wepet2QueryExecutorService {

    Integer executeDeleteAnimalById(String id);

    Page<GetAnimalByIdResponse> executeGetAnimalById(String id, Pageable pageable);

    void exportGetAnimalById(String id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Integer executeDeleteOrgFromLogin(String email);

}