/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wepet.wepet2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.wepet.wepet2.models.query.*;

@Service
public class Wepet2QueryExecutorServiceImpl implements Wepet2QueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Wepet2QueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("wepet2WMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "wepet2TransactionManager")
    @Override
    public Integer executeDeleteAnimalById(String id) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("id", id);

        return queryExecutor.executeNamedQueryForUpdate("deleteAnimalById", params);
    }

    @Transactional(value = "wepet2TransactionManager", readOnly = true)
    @Override
    public Page<GetAnimalByIdResponse> executeGetAnimalById(String id, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("id", id);

        return queryExecutor.executeNamedQuery("getAnimalById", params, GetAnimalByIdResponse.class, pageable);
    }

    @Transactional(value = "wepet2TransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetAnimalById(String id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("id", id);

        QueryProcedureInput<GetAnimalByIdResponse> queryInput = new QueryProcedureInput<>("getAnimalById", params, GetAnimalByIdResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "wepet2TransactionManager")
    @Override
    public Integer executeDeleteOrgFromLogin(String email) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("email", email);

        return queryExecutor.executeNamedQueryForUpdate("deleteOrgFromLogin", params);
    }

}