/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wepet.wepet2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetAnimalByIdResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("name")
    private String name;

    @ColumnAlias("breed")
    private String breed;

    @ColumnAlias("size")
    private String size;

    @ColumnAlias("age")
    private Long age;

    @ColumnAlias("description")
    private String description;

    @ColumnAlias("gender")
    private String gender;

    @ColumnAlias("street")
    private String street;

    @ColumnAlias("city")
    private String city;

    @ColumnAlias("district")
    private String district;

    @ColumnAlias("state")
    private String state;

    @ColumnAlias("country")
    private String country;

    @ColumnAlias("pincode")
    private Long pincode;

    @ColumnAlias("longitude")
    private BigDecimal longitude;

    @ColumnAlias("latitude")
    private BigDecimal latitude;

    @ColumnAlias("is_vaccinated")
    private Boolean isVaccinated;

    @ColumnAlias("animal_type_id")
    private Long animalTypeId;

    @ColumnAlias("image_path")
    private String imagePath;

    @ColumnAlias("is_adopted")
    private Boolean isAdopted;

    @ColumnAlias("organization_id")
    private Long organizationId;

    @ColumnAlias("upload_date")
    private LocalDateTime uploadDate;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBreed() {
        return this.breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public Long getAge() {
        return this.age;
    }

    public void setAge(Long age) {
        this.age = age;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Long getPincode() {
        return this.pincode;
    }

    public void setPincode(Long pincode) {
        this.pincode = pincode;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public Boolean getIsVaccinated() {
        return this.isVaccinated;
    }

    public void setIsVaccinated(Boolean isVaccinated) {
        this.isVaccinated = isVaccinated;
    }

    public Long getAnimalTypeId() {
        return this.animalTypeId;
    }

    public void setAnimalTypeId(Long animalTypeId) {
        this.animalTypeId = animalTypeId;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public Boolean getIsAdopted() {
        return this.isAdopted;
    }

    public void setIsAdopted(Boolean isAdopted) {
        this.isAdopted = isAdopted;
    }

    public Long getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    public LocalDateTime getUploadDate() {
        return this.uploadDate;
    }

    public void setUploadDate(LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetAnimalByIdResponse)) return false;
        final GetAnimalByIdResponse getAnimalByIdResponse = (GetAnimalByIdResponse) o;
        return Objects.equals(getId(), getAnimalByIdResponse.getId()) &&
                Objects.equals(getName(), getAnimalByIdResponse.getName()) &&
                Objects.equals(getBreed(), getAnimalByIdResponse.getBreed()) &&
                Objects.equals(getSize(), getAnimalByIdResponse.getSize()) &&
                Objects.equals(getAge(), getAnimalByIdResponse.getAge()) &&
                Objects.equals(getDescription(), getAnimalByIdResponse.getDescription()) &&
                Objects.equals(getGender(), getAnimalByIdResponse.getGender()) &&
                Objects.equals(getStreet(), getAnimalByIdResponse.getStreet()) &&
                Objects.equals(getCity(), getAnimalByIdResponse.getCity()) &&
                Objects.equals(getDistrict(), getAnimalByIdResponse.getDistrict()) &&
                Objects.equals(getState(), getAnimalByIdResponse.getState()) &&
                Objects.equals(getCountry(), getAnimalByIdResponse.getCountry()) &&
                Objects.equals(getPincode(), getAnimalByIdResponse.getPincode()) &&
                Objects.equals(getLongitude(), getAnimalByIdResponse.getLongitude()) &&
                Objects.equals(getLatitude(), getAnimalByIdResponse.getLatitude()) &&
                Objects.equals(getIsVaccinated(), getAnimalByIdResponse.getIsVaccinated()) &&
                Objects.equals(getAnimalTypeId(), getAnimalByIdResponse.getAnimalTypeId()) &&
                Objects.equals(getImagePath(), getAnimalByIdResponse.getImagePath()) &&
                Objects.equals(getIsAdopted(), getAnimalByIdResponse.getIsAdopted()) &&
                Objects.equals(getOrganizationId(), getAnimalByIdResponse.getOrganizationId()) &&
                Objects.equals(getUploadDate(), getAnimalByIdResponse.getUploadDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getBreed(),
                getSize(),
                getAge(),
                getDescription(),
                getGender(),
                getStreet(),
                getCity(),
                getDistrict(),
                getState(),
                getCountry(),
                getPincode(),
                getLongitude(),
                getLatitude(),
                getIsVaccinated(),
                getAnimalTypeId(),
                getImagePath(),
                getIsAdopted(),
                getOrganizationId(),
                getUploadDate());
    }
}